export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const REMOVE_INGREDIENT = 'REMOVE_INGREDIENT';
export const INIT_INGREDIENTS = 'INIT_INGREDIENTS';
export const INIT_INGREDIENTS_FAILED = 'INIT_INGREDIENTS_FAILED';

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START'
export const PURCHASE_BURGER_SUCCESS = 'PURCHASE_BURGER_SUCCESS';
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const INIT_ORDERS_START = 'INIT_ORDERS_START';
export const INIT_ORDERS_SUCCESS = 'INIT_ORDERS_SUCCESS';
export const INIT_ORDERS_FAIL = 'INIT_ORDERS_FAIL';

export const AUTHENTICATE_START = 'AUTHENTICATE_START';
export const AUTHENTICATE_SUCCESS = 'AUTHENTICATE_SUCCESS';
export const AUTHENTICATE_FAIL = 'AUTHENTICATE_FAIL';
export const AUTHENTICATE_REFRESH = 'AUTHENTICATE_REFRESH';
export const AUTHENTICATE_LOGOUT = 'AUTHENTICATE_LOGOUT';
